### PR TITLE
implement `Selenium::Element#submit`

### PR DESCRIPTION
**Pull request by mamantoha**
Inspired from [Ruby](https://github.com/SeleniumHQ/selenium/blob/0e5bb5b37fd993486cb3bc70fffdda143cbb97b8/rb/lib/selenium/webdriver/remote/bridge.rb#L421-L435) and [Python](https://github.com/SeleniumHQ/selenium/blob/3f6717df6407180f8fae81a85702e7eec5a81093/py/selenium/webdriver/remote/webelement.py#L95-L112) implementations

### CODE REVIEW

**Comment by mamantoha** [comment]
If you are wonder about `ELEMENT_KEY = "element-6066-11e4-a52e-4f735466cecf"` check https://www.w3.org/TR/2015/WD-webdriver-20150827/

image

**Comment by matthewmcgarvey** [comment]
Hey @mamantoha , I'm happy with this change, you've just got the failing format check if you could fix that.

**Comment by mamantoha** [comment]
Hi @matthewmcgarvey . Ameba linter fails are not related to changes in this PR. This is due new version of ameba being released.
You can merge and then run `./bin/ameba --fix`.
Or I can fix the warning here. What should I do?

**Comment by matthewmcgarvey** [comment]
Ahh, sorry about that. I fixed it myself, and thank you for helping out!

**Pull request merged**
